//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeService {
    
    public partial class EmployeeView {
        
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        
        protected global::System.Web.UI.WebControls.Panel alertPanel;
        
        protected global::System.Web.UI.WebControls.Label alertMessage;
        
        protected global::System.Web.UI.WebControls.Literal litAvatar;
        
        protected global::System.Web.UI.WebControls.Literal litFullName;
        
        protected global::System.Web.UI.WebControls.Literal litPosition;
        
        protected global::System.Web.UI.WebControls.Literal litDepartment;
        
        protected global::System.Web.UI.WebControls.Literal litEmiratesId;
        
        protected global::System.Web.UI.WebControls.Literal litPassportNumber;
        
        protected global::System.Web.UI.WebControls.Literal litNationality;
        
        protected global::System.Web.UI.WebControls.Literal litDateOfBirth;
        
        protected global::System.Web.UI.WebControls.Literal litGender;
        
        protected global::System.Web.UI.WebControls.Literal litWorkEmail;
        
        protected global::System.Web.UI.WebControls.Literal litPersonalEmail;
        
        protected global::System.Web.UI.WebControls.Literal litWorkPhone;
        
        protected global::System.Web.UI.WebControls.Literal litPersonalPhone;
        
        protected global::System.Web.UI.WebControls.Literal litEmirates;
        
        protected global::System.Web.UI.WebControls.Literal litCity;
        
        protected global::System.Web.UI.WebControls.Literal litDistrict;
        
        protected global::System.Web.UI.WebControls.Literal litHireDate;
        
        protected global::System.Web.UI.WebControls.Literal litContractType;
        
        protected global::System.Web.UI.WebControls.Literal litEmploymentStatus;
        
        protected global::System.Web.UI.WebControls.Literal litSalaryGrade;
        
        protected global::System.Web.UI.WebControls.Literal litManager;
    }
} 