//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeService {
    
    public partial class AdminEmployeeManagement {
        
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel3;
        
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        
        protected global::System.Web.UI.WebControls.Panel alertPanel;
        
        protected global::System.Web.UI.WebControls.Label alertMessage;
        
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        
        protected global::System.Web.UI.WebControls.Button btnSearch;
        

        
        protected global::System.Web.UI.WebControls.Button btnAddNew;
        
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
        
        protected global::System.Web.UI.WebControls.Label modalTitle;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnEmployeeId;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmiratesId;
        
        protected global::System.Web.UI.WebControls.TextBox txtPassportNumber;
        
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        
        protected global::System.Web.UI.WebControls.TextBox txtNationality;
        
        protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        
        protected global::System.Web.UI.WebControls.TextBox txtHireDate;
        
        protected global::System.Web.UI.WebControls.TextBox txtWorkEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtPersonalEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtWorkPhone;
        
        protected global::System.Web.UI.WebControls.TextBox txtPersonalPhone;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmirates;
        
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        
        protected global::System.Web.UI.WebControls.TextBox txtDistrict;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlContractType;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlEmploymentStatus;
        
        protected global::System.Web.UI.WebControls.TextBox txtSalaryGrade;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentModal;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlPositionModal;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlManager;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlExportFormat;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlExportScope;
        
        protected global::System.Web.UI.WebControls.Button btnExport;
        
        protected global::System.Web.UI.WebControls.Button btnExportSelected;
        
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
} 