//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeService {
    
    public partial class EmployeeView {
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl employeeName;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl employeePosition;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl employeeDepartment;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl employeeId;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl fullName;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl email;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl phone;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl address;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dateOfBirth;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl department;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl position;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl hireDate;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl employmentStatus;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl salary;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl manager;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl emergencyContact;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl emergencyPhone;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl bloodType;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl nationality;
        
        protected global::System.Web.UI.WebControls.Button btnEditProfile;
        
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
        
        protected global::System.Web.UI.WebControls.Button btnPrintProfile;
    }
} 